name: cd

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/src/terraform/**"
      - ".github/workflows/**"

env:
  WORKING_DIRECTORY: ".github/workflows/src/terraform"
  PREFIX: "woof-ai"
  ENVIRONMENT: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5
          terraform_wrapper: false

      - name: Terraform Apply
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_TENANT_SECRET: ${{ secrets.ARM_TENANT_SECRET }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          BACKEND_STORAGE_CONTAINER_NAME: ${{ secrets.BACKEND_STORAGE_CONTAINER_NAME }}
          TV_VAR_prefix: ${{ env.PREFIX }}
          TV_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_BACKEND_KEY: ${{ env.PREFIX}}-${{ env.ENVIRONMENT }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform init \
            -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP_NAME" \
            -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME" \
            -backend-config="container_name=$BACKEND_STORAGE_CONTAINER_NAME" \
            -backend-config="key=$TF_BACKEND_KEY"
          terraform apply --auto-approve
